#:schema node_modules/wrangler/config-schema.json
name = "deskflow-api"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[kv_namespaces]]
binding = "APP_VERSION"
id = "9eaad23626614bccaf775d1af0069a6c"

[[durable_objects.bindings]]
name = "SlowKV"
class_name = "SlowKV"

[[durable_objects.bindings]]
name = "VotesByIP"
class_name = "VotesByIP"

[[migrations]]
tag = "<v1>"
new_sqlite_classes = ["SlowKV"]

[[migrations]]
tag = "<v1>"
new_sqlite_classes = ["VotesByIP"]
